name: New Version

on:
  workflow_run:
    workflows: ["Main"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  check-and-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-venv

      - name: Extract latest version
        id: latest-version
        run: |
          VERSION=$(uv run inv version)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create and push tag if not exists
        run: |
          if ! git rev-parse "v${{ env.version }}" >/dev/null 2>&1; then
            echo "Creating new tag: v${{ env.version }}"
            git tag "v${{ env.version }}"
            git push origin "v${{ env.version }}"
          else
            echo "Tag v${{ env.version }} already exists. Skipping."
          fi
